Class {
	#name : #ABCustomAddressBookExamples,
	#superclass : #Object,
	#traits : 'TABAddressBookModelBuilder + TEParametrizedExamplesListExtension + TABAddressBookParametrizedExamples',
	#classTraits : 'TABAddressBookModelBuilder classTrait + TEParametrizedExamplesListExtension classTrait + TABAddressBookParametrizedExamples classTrait',
	#category : #'AddressBook-Scenarios'
}

{ #category : #accessing }
ABCustomAddressBookExamples class >> label [
	^  'Custom Address Book'
]
